---
kind: BuildConfig
apiVersion: v1
metadata:
  name: grpc-greetings-client
  labels:
    app: test-grpc
spec:
  source:
    type: Git
    contextDir: GrpcGreeterClient/
    git:
      uri: https://github.com/yrenard-dedalus/grpc-greetings.git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: grpc-greetings-client:0.1
  triggers:
  - type: ConfigChang

---
kind: ImageStream
apiVersion: v1
metadata:
  name: grpc-greetings-client
  labels:
    app: test-grpc
spec:
  tags:
    - name: "0.1"
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: grpc-greetings-client
  labels:
    deploymentConfig: grpc-greetings-client
    app: test-grpc
spec:
  replicas: 2
  selector:
    deploymentConfig: grpc-greetings-client
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 120
      maxUnavailable: "10%"
  template:
    metadata:
      labels:
        deploymentConfig: grpc-greetings-client
        app: test-grpc
      name: grpc-greetings-client
    spec:
      containers:
      - name: grpc-greetings-client
        image: grpc-greetings-client:0.1
        imagePullPolicy: Always
        ports: 
        - name: grpc
          containerPort: 5001
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - grpc-greetings-client
      from:
        kind: ImageStreamTag
        name: grpc-greetings-client:0.1

---
kind: Service
apiVersion: v1
metadata:
  name: grpc-greetings-client
  labels:
    app: test-grpc
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 5001
    targetPort: 5001
  selector:
    deploymentConfig: grpc-greetings-client